version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    command: npm run dev
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev

